import 'package:e_commerce_app/models/product.dart';

class MyProducts {
  static List<Product> allProducts = [
    Product(
      id: 1, 
      name: 'Nike Air Max 1',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 2',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 3',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 4',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 5',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 11',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 22',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 33',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 44',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 55',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    
  ];

   static List<Product> sneakersList = [
    Product(
      id: 1, 
      name: 'Nike Air Max 1',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 2',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 3',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 4',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 5',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
  ];

   static List<Product> jacketsList = [
    Product(
      id: 1, 
      name: 'Nike Air Max 11',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 22',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 33',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 44',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
    Product(
      id: 1, 
      name: 'Nike Air Max 55',
      category: "Trending Now",
      price: 180.00, 
      description: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
      image: "assets/kedi.jpg", 
      quantity: 1,
    ),
  ];

}